import os
import time
import json
import asyncio
import re
from datetime import datetime, timezone, timedelta
from typing import Any, Optional, Dict, List
import statistics

import httpx
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

from google import genai
from google.genai import types as genai_types
from community_discovery import discover_communities, load_community_database, classify_subreddit  # type: ignore

# Model name for Gemini (google-genai SDK)
_GEMINI_MODEL = "gemini-2.0-flash"

def _get_gemini_client():
    """Create a Gemini client lazily, only when API key is present.
    Returns None if GEMINI_API_KEY is not set, so the rest of the
    pipeline (data ingestion, scoring, report) still runs without AI."""
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        return None
    return genai.Client(api_key=api_key)

ARCTIC_SHIFT_BASE = "https://arctic-shift.photon-reddit.com/api"

def _set_cell_background(cell, fill_hex: str) -> None:
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), fill_hex)
    tcPr.append(shd)

def _add_heading(doc, text, level=1, size=16, bold=True):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(size)
    run.bold = bold
    return p

class DailyIntelligencePipeline:
    def __init__(self, output_dir: str, db_path: str = None, tracking_path: str = None):
        self.output_dir = output_dir
        self.db_path = db_path or os.environ.get("DB_PATH", "./data/community_database.json")
        self.tracking_path = tracking_path or os.environ.get("TRACKING_PATH", "./outputs/post_tracking.json")
        self.db = []
        self.tracking = {}
        self.new_discoveries = []
        self.community_stats = {}
        self.model = _GEMINI_MODEL  # model name string, client created lazily
        self.stats = {
            "scanned_today": 0,
            "new_posts_intake": 0,
            "velocity_checked": 0,
            "pass_a_duration": 0,
            "pass_b_duration": 0,
            "peaked_today": 0,
            "paginated_subs": 0,
            "total_in_db": 0,
            "total_tracked": 0,
            "oldest_tracked": 0
        }

    async def initialize_db(self):
        import sys
        if not os.path.exists(self.db_path):
            print("❌ CRITICAL: community_database.json not found")
            print("   Expected location: data/community_database.json")
            print()
            print("   This file is generated by running:")
            print("   python run_weekly_discovery.py")
            print("   on your local machine, then committing:")
            print("   git add data/community_database.json")
            print("   git commit -m 'Weekly database update'")
            print("   git push")
            print()
            print("   The daily pipeline cannot run without this file.")
            print("   Run the weekly discovery on your laptop first.")
            sys.exit(1)
            
        with open(self.db_path, "r", encoding="utf-8") as f:
            db_data = json.load(f)
            
        self.db = db_data.get("communities", [])
        db_date = db_data.get("last_updated", "unknown")
        db_count = len(self.db)
        
        print(f"✅ Loaded community database:")
        print(f"   Communities: {db_count}")
        print(f"   Last updated: {db_date}")
        
        # Warn if database is more than 14 days old
        if db_data.get("last_updated"):
            try:
                updated = datetime.fromisoformat(
                    db_data["last_updated"].replace("Z", "+00:00")
                )
                age_days = (
                    datetime.now(timezone.utc) - updated
                ).days
                if age_days > 14:
                    print(f"⚠  WARNING: Database is {age_days} days old.")
                    print("   Run weekly discovery locally to refresh it.")
            except:
                pass

        self.stats["total_in_db"] = len(self.db)
        self.cleanup_tracking_db()

    def cleanup_tracking_db(self):
        if os.path.exists(self.tracking_path):
            try:
                with open(self.tracking_path, "r", encoding="utf-8") as f:
                    self.tracking = json.load(f)
            except Exception:
                self.tracking = {}
                
        now = datetime.now(timezone.utc)
        to_delete = []
        peaked_removed = 0
        
        for pid, data in list(self.tracking.items()):
            if "first_seen" not in data: 
                first_seen = now
            else:
                first_seen = datetime.fromisoformat(data["first_seen"])
                
            age_hours = (now - first_seen).total_seconds() / 3600
            if "created_utc" in data:
                age_hours = (now - datetime.fromtimestamp(data["created_utc"], timezone.utc)).total_seconds() / 3600
                
            status = data.get("status", "")
            
            if age_hours > 240:
                to_delete.append(pid)
            elif status == "peaked" and age_hours > 96:
                to_delete.append(pid)
                peaked_removed += 1
            elif age_hours > 96:
                obs_list = data.get("observations", [])
                if len(obs_list) > 3:
                    compressed = []
                    last_kept = None
                    for o in obs_list:
                        o_ts = datetime.fromisoformat(o["utc"])
                        if last_kept is None or (o_ts - last_kept).total_seconds() >= 86400:
                            compressed.append(o)
                            last_kept = o_ts
                    if obs_list and obs_list[-1] not in compressed:
                        compressed.append(obs_list[-1])
                    data["observations"] = compressed
                    
        for pid in to_delete:
            del self.tracking[pid]
            
        print(f"Tracking DB Cleanup: {len(self.tracking)} active posts, {peaked_removed} peaked removed.")

    async def run_stage_1(self, client):
        start_a = time.time()
        now = datetime.now(timezone.utc)
        after_24h = int(now.timestamp() - 86400)
        
        sem_a = asyncio.Semaphore(15)
        paginated_subs = 0
        new_posts = 0
        scanned_comms = 0
        
        async def fetch_intake(sub_entry):
            nonlocal new_posts, paginated_subs, scanned_comms
            sub_name = sub_entry["name"]
            has_paginated = False
            all_posts = []
            before_ts = int(now.timestamp())
            
            async with sem_a:
                while True:
                    for _ in range(3):
                        try:
                            resp = await client.get(
                                f"{ARCTIC_SHIFT_BASE}/posts/search",
                                params={"subreddit": sub_name, "limit": 100, "sort": "desc", "after": after_24h, "before": before_ts},
                                timeout=10.0
                            )
                            if resp.status_code == 200:
                                batch = resp.json().get("data", [])
                                break
                            elif resp.status_code == 429:
                                await asyncio.sleep(2)
                        except:
                            batch = []
                            await asyncio.sleep(1)
                    else:
                        batch = []
                        
                    all_posts.extend(batch)
                    
                    if len(batch) == 100:
                        has_paginated = True
                        before_ts = int(batch[-1].get("created_utc", before_ts)) - 1
                        await asyncio.sleep(0.1)
                    else:
                        break
                        
                if has_paginated: paginated_subs += 1
                scanned_comms += 1
                
                for p in all_posts:
                    pid = p["id"]
                    score = p.get("score", 0)
                    comments = p.get("num_comments", 0)
                    created_utc = p.get("created_utc", 0)
                    hours_since = (now.timestamp() - created_utc) / 3600
                    
                    obs = {
                        "utc": now.isoformat(),
                        "score": score,
                        "comments": comments,
                        "hours_since_posted": hours_since
                    }
                    
                    if pid not in self.tracking:
                        self.tracking[pid] = {
                            "id": pid,
                            "title": p.get("title", ""),
                            "subreddit": sub_name,
                            "author": p.get("author", ""),
                            "url": f"https://reddit.com{p.get('permalink', '')}",
                            "created_utc": created_utc,
                            "first_seen": now.isoformat(),
                            "first_seen_score": score,
                            "first_seen_comments": comments,
                            "observations": [obs],
                            "latest_score": score,
                            "latest_comments": comments,
                            "latest_velocity_24h": 0,
                            "peak_score": score,
                            "status": "new",
                            "last_checked": now.isoformat()
                        }
                        new_posts += 1
                    else:
                        data = self.tracking[pid]
                        data["observations"].append(obs)
                        data["latest_score"] = score
                        data["latest_comments"] = comments
                        if score > data.get("peak_score", 0):
                            data["peak_score"] = score
                        data["last_checked"] = now.isoformat()
            
                if scanned_comms % 100 == 0:
                    print(f"Pass A: Scanned {scanned_comms}/{len(self.db)} communities...")
                    await asyncio.sleep(0.1)

        print("Starting Pass A: Intake Pass")
        await asyncio.gather(*[fetch_intake(c) for c in self.db])
        
        self.stats["scanned_today"] = scanned_comms
        self.stats["new_posts_intake"] = new_posts
        self.stats["pass_a_duration"] = time.time() - start_a
        self.stats["paginated_subs"] = paginated_subs
        
        # Pass B: Velocity Pass
        start_b = time.time()
        sem_b = asyncio.Semaphore(20)
        
        velocity_candidates = []
        for pid, data in self.tracking.items():
            if "created_utc" not in data: continue
            age_hours = (now.timestamp() - data["created_utc"]) / 3600
            last_checked_hours = 0
            if "last_checked" in data:
                last_checked = datetime.fromisoformat(data["last_checked"])
                last_checked_hours = (now - last_checked).total_seconds() / 3600
                
            if 24 <= age_hours <= 96 and last_checked_hours >= 20 and data.get("status") != "peaked":
                velocity_candidates.append(data)
                
        vel_checked = 0
        peaked_today = 0
        
        async def fetch_velocity(data):
            nonlocal vel_checked, peaked_today
            pid = data["id"]
            async with sem_b:
                for _ in range(3):
                    try:
                        resp = await client.get(
                            f"{ARCTIC_SHIFT_BASE}/posts/search",
                            params={"id": pid, "limit": 1},
                            timeout=10.0
                        )
                        if resp.status_code == 200:
                            posts = resp.json().get("data", [])
                            break
                        elif resp.status_code == 429:
                            await asyncio.sleep(2)
                    except:
                        posts = []
                        await asyncio.sleep(1)
                else:
                    posts = []
                    
                if posts:
                    p = posts[0]
                    current_score = p.get("score", 0)
                    current_comments = p.get("num_comments", 0)
                    hours_since = (now.timestamp() - data["created_utc"]) / 3600
                    
                    data["observations"].append({
                        "utc": now.isoformat(),
                        "score": current_score,
                        "comments": current_comments,
                        "hours_since_posted": hours_since
                    })
                    
                    data["latest_score"] = current_score
                    data["latest_comments"] = current_comments
                    data["last_checked"] = now.isoformat()
                    if current_score > data.get("peak_score", 0):
                        data["peak_score"] = current_score

                # Always compute hours_since — needed for peaked detection below
                # even when Arctic Shift returned no data for this post ID
                hours_since = (now.timestamp() - data["created_utc"]) / 3600
                        
                obs_list = data["observations"]
                obs_24h = None
                obs_48h = None
                min_diff_24 = 999999
                min_diff_48 = 999999
                
                for o in obs_list:
                    o_ts = datetime.fromisoformat(o["utc"])
                    diff_sec = abs(86400 - (now - o_ts).total_seconds())
                    if diff_sec < min_diff_24 and diff_sec <= 28800:
                        min_diff_24 = diff_sec
                        obs_24h = o
                        
                    diff_sec_48 = abs(172800 - (now - o_ts).total_seconds())
                    if diff_sec_48 < min_diff_48 and diff_sec_48 <= 28800:
                        min_diff_48 = diff_sec_48
                        obs_48h = o
                        
                vel_24 = 0
                vel_48 = 0
                accel = 0
                current_score = data["latest_score"]
                
                if obs_24h: vel_24 = current_score - obs_24h["score"]
                if obs_48h: vel_48 = current_score - obs_48h["score"]
                    
                if obs_24h and obs_48h:
                    vel_prior = vel_48 - vel_24
                    accel = vel_24 - vel_prior
                    
                data["latest_velocity_24h"] = vel_24
                data["latest_velocity_48h"] = vel_48
                data["acceleration"] = accel
                
                if vel_24 <= 2 and current_score == data.get("peak_score", 0) and hours_since > 96:
                    data["status"] = "peaked"
                    peaked_today += 1
                elif vel_24 > 0 and accel > 0:
                    data["status"] = "accelerating"
                elif vel_24 > 0:
                    data["status"] = "growing"
                elif vel_24 <= 0:
                    data["status"] = "declining"
                    
                vel_checked += 1
                if vel_checked % 50 == 0:
                    print(f"Pass B: Checked {vel_checked}/{len(velocity_candidates)} posts...")
                    
        print(f"Starting Pass B: Velocity Pass ({len(velocity_candidates)} candidates)")
        await asyncio.gather(*[fetch_velocity(d) for d in velocity_candidates])
        
        self.stats["pass_b_duration"] = time.time() - start_b
        self.stats["velocity_checked"] = vel_checked
        self.stats["peaked_today"] = peaked_today
        self.stats["total_tracked"] = len(self.tracking)
        
        oldest = 0
        if self.tracking:
            oldest = max((now.timestamp() - d["created_utc"]) / 3600 for d in self.tracking.values() if "created_utc" in d)
        self.stats["oldest_tracked"] = oldest
        
        os.makedirs(os.path.dirname(self.tracking_path), exist_ok=True)
        with open(self.tracking_path, "w", encoding="utf-8") as f:
            json.dump(self.tracking, f, indent=2)

    def run_stage_2(self):
        now = datetime.now(timezone.utc)
        candidates = []
        
        # Calculate dynamic baselines per community from last 30 days
        sub_posts = {}
        for d in self.tracking.values():
            if "created_utc" not in d: continue
            age_days = (now.timestamp() - d["created_utc"]) / 86400
            if age_days <= 30:
                sub = d["subreddit"]
                if sub not in sub_posts: sub_posts[sub] = []
                sub_posts[sub].append(d)
                
        dynamic_baselines = {}
        for sub, entry in zip([e["name"] for e in self.db], self.db):
            static_score = entry.get("baseline_avg_score", 10)
            posts = sub_posts.get(sub, [])
            if len(posts) >= 10:
                avg_s = sum(p["latest_score"] for p in posts) / len(posts)
                avg_v = sum(p.get("latest_velocity_24h", 0) for p in posts) / len(posts)
                dynamic_baselines[sub] = {"score": max(1, avg_s), "velocity": max(1, avg_v), "comments": max(1, sum(p["latest_comments"] for p in posts)/len(posts))}
            else:
                dynamic_baselines[sub] = {"score": max(1, static_score), "velocity": max(1, static_score/2), "comments": max(1, static_score/5)}
        
        # Build cross-community keyword tracking
        stop_words = {"the", "a", "is", "are", "i", "my", "to", "and", "of", "in", "for", "on", "with", "it", "this", "that", "how", "what", "can", "you", "do", "we", "not", "be", "have"}
        word_to_subs = {}
        for d in self.tracking.values():
            if "title" not in d: continue
            title_words = set(w for w in re.findall(r'\b[a-z]{4,}\b', d["title"].lower()) if w not in stop_words)
            for w in title_words:
                if w not in word_to_subs: word_to_subs[w] = set()
                word_to_subs[w].add(d["subreddit"])

        cross_community_words = {w for w, subs in word_to_subs.items() if len(subs) >= 3}
        self.trends_data = [{"keyword": w, "total_mentions": len(subs), "subreddits_mentioning": list(subs)} for w, subs in word_to_subs.items() if len(subs) >= 3]

        # Populate community stats for stage 5
        for sub in [e["name"] for e in self.db]:
            # calculate today's avg for the table
            posts_today = [p for p in sub_posts.get(sub, []) if (now.timestamp() - p["created_utc"]) <= 86400]
            today_avg = sum(p["latest_score"] for p in posts_today) / len(posts_today) if posts_today else 0
            b = dynamic_baselines[sub]["score"]
            # get subscribers from db
            subscribers = next((e["subscribers"] for e in self.db if e["name"] == sub), 0)
            self.community_stats[sub] = {
                "baseline_avg": b,
                "today_avg": today_avg,
                "subscribers": subscribers
            }

        # Find viral candidates
        for pid, data in self.tracking.items():
            if "created_utc" not in data: continue
            age_hours = (now.timestamp() - data["created_utc"]) / 3600
            
            score = data["latest_score"]
            velocity_24h = data.get("latest_velocity_24h", 0)
            accel = data.get("acceleration", 0)
            comments = data["latest_comments"]
            status = data.get("status", "")
            
            b_data = dynamic_baselines.get(data["subreddit"], {"score": 10, "velocity": 5, "comments": 2})
            b_score = b_data["score"]
            b_vel = b_data["velocity"]
            b_comms = b_data["comments"]
            
            crit_1 = score >= max(50, 3 * b_score)
            crit_2 = velocity_24h >= max(30, 2 * b_vel)
            crit_3 = accel > 0 and velocity_24h >= 20
            crit_4 = comments >= 3 * b_comms and score >= 20
            
            title_words = set(re.findall(r'\b[a-z]{4,}\b', data.get("title", "").lower()))
            crit_5 = bool(title_words.intersection(cross_community_words))
            
            priority = "LOW"
            if status != "peaked":
                if (crit_1 or crit_2) and accel > 0 and age_hours < 48:
                    priority = "CRITICAL"
                elif (crit_1 or crit_2) and age_hours < 96:
                    priority = "HIGH"
                elif crit_3 or crit_4 or (velocity_24h >= b_vel and age_hours < 72):
                    priority = "MEDIUM"
                elif crit_5 or velocity_24h > 0:
                    priority = "LOW"
            else:
                priority = "LOW" # Peaked posts excluded from high tiers
                
            if priority != "LOW":
                candidates.append({
                    "id": pid,
                    "data": data,
                    "priority": priority,
                    "signals": {"1": crit_1, "2": crit_2, "3": crit_3, "4": crit_4, "5": crit_5},
                    "actual_age_hours": age_hours
                })
                
        return candidates

    async def run_stage_3(self, client, candidates):
        sem = asyncio.Semaphore(5)
        now = datetime.now(timezone.utc)
        
        async def deep_dive(cand):
            pid = cand["id"]
            data = cand["data"]
            priority = cand["priority"]
            actual_age_hours = cand["actual_age_hours"]
            
            async with sem:
                try:
                    resp = await client.get(f"{ARCTIC_SHIFT_BASE}/posts/search", params={"id": pid}, timeout=10.0)
                    if resp.status_code == 200 and resp.json().get("data"):
                        data["body"] = resp.json()["data"][0].get("selftext", "")
                except:
                    pass
                    
                if priority in ["CRITICAL", "HIGH"]:
                    try:
                        clean_id = pid.replace("t3_", "")
                        resp = await client.get(f"{ARCTIC_SHIFT_BASE}/comments/search", params={"link_id": clean_id, "limit": 100, "sort": "desc"}, timeout=10.0)
                        if resp.status_code == 200:
                            comms = resp.json().get("data", [])
                            comms.sort(key=lambda x: x.get("score", 0), reverse=True)
                            data["top_comments"] = comms[:15]
                            
                            for c in data["top_comments"]:
                                mentions = re.findall(r'r\/([a-zA-Z0-9_]+)', c.get('body', ''))
                                for m in mentions:
                                    if not any(entry["name"].lower() == m.lower() for entry in self.db):
                                        try:
                                            about_resp = await client.get(f"https://www.reddit.com/r/{m}/about.json", headers={"User-Agent": "ThreadVault/1.0 (community tracker)"})
                                            if about_resp.status_code == 200:
                                                about_data = about_resp.json().get("data", {})
                                                subscribers = about_data.get("subscribers", 0)
                                                if 10000 <= subscribers <= 1000000 and about_data.get("subreddit_type") == "public" and not about_data.get("over18", False):
                                                    self.db.append({
                                                        "name": m,
                                                        "display_name": about_data.get("display_name_prefixed", f"r/{m}"),
                                                        "title": about_data.get("title", ""),
                                                        "description": about_data.get("public_description", ""),
                                                        "subscribers": subscribers,
                                                        "active_user_count": about_data.get("active_user_count", 0) or 0,
                                                        "engagement_ratio": 0,
                                                        "activity_score": 50,
                                                        "category": classify_subreddit(m, about_data.get("title", "")),
                                                        "created_utc": int(about_data.get("created_utc", 0)),
                                                        "last_seen": datetime.now(timezone.utc).isoformat()
                                                    })
                                                    self.new_discoveries.append({
                                                        "name": m,
                                                        "subscribers": subscribers,
                                                        "source": data["subreddit"]
                                                    })
                                                    print(f"New community discovered: r/{m}")
                                        except Exception:
                                            pass
                    except:
                        data["top_comments"] = []
                else:
                    data["top_comments"] = []
                    
                data["full_content_fetched"] = True
                data["deep_dive_date"] = now.isoformat()
                
                if actual_age_hours <= 24: stage = "early_momentum"
                elif 24 < actual_age_hours <= 48: stage = "peak_velocity"
                elif 48 < actual_age_hours <= 72: stage = "sustained_viral"
                elif 72 < actual_age_hours <= 96: stage = "late_viral"
                elif data.get("latest_velocity_24h", 0) < 10 and actual_age_hours > 96: stage = "peaked"
                else: stage = "declining"
                
                data["stage_of_virality"] = stage
                data["hours_since_posted"] = actual_age_hours
                
            await asyncio.sleep(0.5)

        print(f"Starting Stage 3: Deep Dive on {len(candidates)} candidates")
        tasks = [deep_dive(c) for c in candidates]
        await asyncio.gather(*tasks)

        with open(self.tracking_path, "w", encoding="utf-8") as f:
            json.dump(self.tracking, f, indent=2)

    async def analyze_post(self, sem, cand):
        async with sem:
            data = cand["data"]
            if cand["priority"] not in ["CRITICAL", "HIGH"]: return
            
            sys_prompt = "You are an elite market research analyst and startup opportunity spotter. You analyze Reddit viral posts to extract actionable business insights for SaaS founders and indie hackers. You are brutally direct, specific, and never vague. Every insight you give must be immediately actionable. Respond ONLY in valid JSON."
            
            comments_text = "\n".join([f"u/{c.get('author')} ({c.get('score')}): {c.get('body')}" for c in data.get("top_comments", [])])
            
            user_prompt = f"""Analyze this viral Reddit post and extract business intelligence for a founder.
SUBREDDIT: r/{data['subreddit']}

POST LIFECYCLE DATA:
Hours since posted: {data.get('hours_since_posted', 0):.1f}
Stage: {data.get('stage_of_virality', 'unknown')}
Score at first sight: {data.get('first_seen_score', 0)}
Score now: {data['latest_score']}
Score growth in 24h: +{data.get('latest_velocity_24h', 0)}
Score growth in 48h: +{data.get('latest_velocity_48h', 0)}

POST BODY:
Title: {data['title']}
{data.get('body', '')[:1000]}

TOP COMMENTS:
{comments_text[:2000]}

Return a JSON object with EXACTLY these fields:
{{
  "opportunity_score": integer 1-10,
  "why_it_went_viral": "string",
  "core_pain_point": "string",
  "who_has_this_pain": "string",
  "saas_opportunity": "string or null",
  "existing_solutions_mentioned": ["string"],
  "gaps_in_existing_solutions": "string or null",
  "urgency_signal": "build_now|validate_first|monitor|pass",
  "first_action_if_pursuing": "string",
  "market_size_signal": "massive|medium|niche|unknown",
  "competition_level": "wide_open|some_competition|crowded|dominated",
  "one_line_summary": "string",
  "time_sensitivity": "act_in_hours|act_today|act_this_week|no_rush",
  "virality_reason_technical": "string",
  "is_this_a_repeated_complaint": "first_time_seen|recurring_theme|seasonal_spike",
  "competitive_window": "string"
}}
"""
            try:
                client = _get_gemini_client()
                if client is None:
                    data["ai"] = None
                    return
                resp = await client.aio.models.generate_content(
                    model=_GEMINI_MODEL,
                    contents=sys_prompt + "\n\n" + user_prompt,
                    config=genai_types.GenerateContentConfig(
                        response_mime_type="application/json"
                    )
                )
                ai_data = json.loads(resp.text)
                data["ai"] = ai_data
            except Exception as e:
                data["ai"] = None
            
            await asyncio.sleep(1)

    async def run_stage_4(self, candidates, skip_ai=False):
        if skip_ai:
            print("Skipping AI analysis (Test Mode)")
            for cand in candidates:
                if cand["priority"] in ["CRITICAL", "HIGH"]:
                    cand["data"]["ai"] = {"time_sensitivity": "monitor", "opportunity_score": 0, "first_action_if_pursuing": "[AI analysis skipped in test mode]"}
            return {}
        if not os.environ.get("GEMINI_API_KEY"):
            print("WARNING: GEMINI_API_KEY not set. Skipping AI analysis.")
            return {}

        sem = asyncio.Semaphore(2)
        tasks = [self.analyze_post(sem, cand) for cand in candidates]
        await asyncio.gather(*tasks)
        return {}

    def run_stage_5(self, candidates, test_mode=False):
        doc = Document()
        
        def add_box(label, bg_color, lines):
            tbl = doc.add_table(rows=1, cols=1)
            cell = tbl.cell(0,0)
            _set_cell_background(cell, bg_color)
            p = cell.paragraphs[0]
            r = p.add_run(label + "\n")
            r.bold = True
            for line in lines:
                cell.add_paragraph(line)

        # Categorize posts
        act_in_hours = []
        act_today = []
        act_this_week = []
        monitor = []
        
        for cand in candidates:
            if cand["priority"] == "LOW": continue
            data = cand["data"]
            ai = data.get("ai")
            ts = ai.get("time_sensitivity", "monitor") if ai else "monitor"
            ts = ts.lower()
            
            if "hours" in ts: act_in_hours.append(cand)
            elif "today" in ts: act_today.append(cand)
            elif "week" in ts: act_this_week.append(cand)
            else: monitor.append(cand)
            
        for group in [act_in_hours, act_today, act_this_week, monitor]:
            group.sort(key=lambda x: x["data"].get("latest_velocity_24h", 0), reverse=True)

        # PAGE 1 — COVER + URGENCY DASHBOARD
        _add_heading(doc, "ThreadVault Daily Intelligence", size=20)
        p = doc.add_paragraph()
        p.add_run(f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}").italic = True
        
        if test_mode:
            doc.add_paragraph()
            add_box("⚠ TEST MODE REPORT — 3 subreddits only", "FFDDDD", [
                "This is not a real intelligence report.",
                "Run without test_mode for full coverage."
            ])
            
        doc.add_paragraph()
        p = doc.add_paragraph()
        pct = int((self.stats['scanned_today'] / max(1, self.stats['total_in_db'])) * 100)
        p.add_run(f"✅ {self.stats['scanned_today']} communities scanned today ({pct}% of your 10K-1M database)").bold = True
        
        doc.add_paragraph()
        
        tbl = doc.add_table(rows=4, cols=2)
        tbl.style = "Table Grid"
        
        rows = [
            ("⚡ ACT IN HOURS", f"{len(act_in_hours)} posts", "These are at PEAK virality RIGHT NOW.\nEvery hour you wait, others see this too.", "FFE6E6"),
            ("🔴 ACT TODAY", f"{len(act_today)} posts", "24-48 hours of peak remaining.", "FFEBCC"),
            ("🟡 ACT THIS WEEK", f"{len(act_this_week)} posts", "Still early stage. You have time.", "FFFFE6"),
            ("🟢 MONITOR", f"{len(monitor)} posts", "Building slowly. Check again tomorrow.", "E6FFE6")
        ]
        
        for i, (title, count, desc, bg) in enumerate(rows):
            cell0 = tbl.cell(i,0)
            _set_cell_background(cell0, bg)
            p0 = cell0.paragraphs[0]
            p0.add_run(title).bold = True
            p0.add_run(f"\n{desc}")
            
            cell1 = tbl.cell(i,1)
            _set_cell_background(cell1, bg)
            p1 = cell1.paragraphs[0]
            p1.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            p1.add_run(count).bold = True
            
        doc.add_page_break()

        # Helper to generate post cards
        def generate_cards(title, post_group):
            _add_heading(doc, title, size=16)
            if not post_group:
                doc.add_paragraph("No posts in this category today.")
                doc.add_page_break()
                return
                
            for cand in post_group:
                data = cand["data"]
                ai = data.get("ai") or {}
                
                score = data["latest_score"]
                vel = data.get("latest_velocity_24h", 0)
                comments = data["latest_comments"]
                
                card_title = f"{title.split('SECTION')[0].strip()} — {data.get('hours_since_posted', 0):.1f}h old"
                
                lines = [
                    f"\"{data.get('title')}\"",
                    f"r/{data['subreddit']} • ⬆ {score} (+{vel} in 24h) • 💬 {comments} • Stage: {data.get('stage_of_virality')}",
                    "",
                    f"Opportunity Score: {ai.get('opportunity_score', '?')}/10 • {ai.get('urgency_signal', 'Unknown')}",
                    "",
                    f"Core Pain: {ai.get('core_pain_point', '...')}",
                    f"Build: {ai.get('saas_opportunity', '...')}",
                    "",
                    f"✅ DO THIS NOW: {ai.get('first_action_if_pursuing', '...')}",
                    f"⏰ Competitive Window: {ai.get('competitive_window', '...')}",
                    "",
                    f"Reddit URL: {data.get('url')}"
                ]
                
                bg = "F2F2F2"
                if "HOURS" in title: bg = "FFE6E6"
                elif "TODAY" in title: bg = "FFEBCC"
                elif "WEEK" in title: bg = "FFFFE6"
                
                add_box(card_title, bg, lines)
                doc.add_paragraph()
            doc.add_page_break()

        # Pages 2, 3, 4
        generate_cards("⚡ ACT IN HOURS SECTION", act_in_hours)
        generate_cards("🔴 ACT TODAY SECTION", act_today)
        generate_cards("🟡 ACT THIS WEEK SECTION", act_this_week)

        # PAGE 5 — VELOCITY LEADERBOARD
        _add_heading(doc, "Fastest Growing Posts Right Now", size=16)
        doc.add_paragraph(f"Across all {len(self.db)} communities tracked")
        
        all_posts = sorted([c for c in candidates if c["priority"] != "LOW"], key=lambda x: x["data"].get("latest_velocity_24h", 0), reverse=True)[:25]
        
        vtbl = doc.add_table(rows=1+len(all_posts), cols=6)
        vtbl.style = "Table Grid"
        for i, h in enumerate(["Rank", "Post Title", "Subreddit", "Score", "+24h", "Age"]): vtbl.cell(0,i).text = h
        
        for i, cand in enumerate(all_posts, 1):
            data = cand["data"]
            vtbl.cell(i,0).text = str(i)
            t = data.get("title", "")
            vtbl.cell(i,1).text = t[:30] + "..." if len(t) > 30 else t
            vtbl.cell(i,2).text = f"/{data['subreddit']}"
            vtbl.cell(i,3).text = str(data["latest_score"])
            vtbl.cell(i,4).text = f"+{data.get('latest_velocity_24h', 0)}"
            vtbl.cell(i,5).text = f"{data.get('hours_since_posted', 0):.0f}h"
            
        doc.add_page_break()

        # PAGE 6 — CROSS-COMMUNITY TRENDS
        _add_heading(doc, "Cross-Community Trends", size=16)
        if hasattr(self, "trends_data") and self.trends_data:
            sorted_trends = sorted(self.trends_data, key=lambda x: x["total_mentions"], reverse=True)
            for t in sorted_trends:
                doc.add_paragraph(f"Keyword: '{t['keyword']}'\nFound in: {', '.join(t['subreddits_mentioning'])}").bold = True
                doc.add_paragraph()
        else:
            doc.add_paragraph("No significant cross-community trends detected today.")
        doc.add_page_break()

        # PAGE 7 — NEWLY DISCOVERED COMMUNITIES
        _add_heading(doc, "Newly Discovered Communities", size=16)
        if self.new_discoveries:
            for nd in self.new_discoveries:
                doc.add_paragraph(f"r/{nd['name']} — {nd['subscribers']} members — Discovered via mention in r/{nd['source']}")
        else:
            doc.add_paragraph("No new communities discovered today.")
        doc.add_page_break()

        # PAGE 8 — FULL COMMUNITY ACTIVITY TABLE
        _add_heading(doc, "Full Community Activity Table", size=16)
        
        comm_stats_list = []
        for name, stats in self.community_stats.items():
            ratio = stats["today_avg"] / max(stats["baseline_avg"], 1)
            sig = "➡ NORMAL"
            if ratio >= 2.0: sig = "🔥 SPIKE"
            elif ratio >= 1.3: sig = "📈 UP"
            elif ratio < 0.5: sig = "📉 QUIET"
            
            comm_stats_list.append({
                "name": name,
                "signal": sig,
                "subscribers": stats["subscribers"],
                "baseline": stats["baseline_avg"],
                "today": stats["today_avg"],
                "ratio": ratio
            })
            
        comm_stats_list.sort(key=lambda x: x["ratio"], reverse=True)
        
        ctbl = doc.add_table(rows=1+len(comm_stats_list), cols=5)
        ctbl.style = "Table Grid"
        for i, h in enumerate(["Community", "Signal", "Members", "Baseline", "Today"]): ctbl.cell(0,i).text = h
        
        for i, c in enumerate(comm_stats_list, 1):
            ctbl.cell(i,0).text = f"r/{c['name']}"
            ctbl.cell(i,1).text = c["signal"]
            
            sub_str = f"{c['subscribers']/1000:.0f}K" if c['subscribers'] >= 1000 else str(c['subscribers'])
            if c['subscribers'] >= 1000000: sub_str = f"{c['subscribers']/1000000:.1f}M"
            
            ctbl.cell(i,2).text = sub_str
            ctbl.cell(i,3).text = f"avg: {c['baseline']:.0f}"
            ctbl.cell(i,4).text = f"avg: {c['today']:.0f}"
            
        doc.add_page_break()
        
        # PAGE 9 - COVERAGE & RELIABILITY
        _add_heading(doc, "Coverage & Reliability", size=16)
        doc.add_paragraph(f"Communities in database:        {self.stats['total_in_db']}")
        doc.add_paragraph(f"Communities scanned today:      {self.stats['scanned_today']}")
        doc.add_paragraph(f"Coverage rate:                  {pct}%")
        doc.add_paragraph("")
        doc.add_paragraph(f"New posts ingested today:       {self.stats['new_posts_intake']}")
        doc.add_paragraph(f"Posts velocity-checked today:   {self.stats['velocity_checked']}")
        doc.add_paragraph(f"Active posts being tracked:     {self.stats['total_tracked']}")
        doc.add_paragraph("")
        doc.add_paragraph(f"Pass A duration:                {int(self.stats['pass_a_duration']//60)}m {int(self.stats['pass_a_duration']%60)}s")
        doc.add_paragraph(f"Pass B duration:                {int(self.stats['pass_b_duration']//60)}m {int(self.stats['pass_b_duration']%60)}s")
        doc.add_paragraph("")
        doc.add_paragraph(f"Oldest tracked post:            {self.stats['oldest_tracked']:.1f} hours old (96h max)")
        doc.add_paragraph(f"Posts that peaked today:        {self.stats['peaked_today']}")
        doc.add_paragraph("")
        doc.add_paragraph(f"Posts missed due to 100-post\npagination limit triggered:     {self.stats['paginated_subs']} subreddits")
        doc.add_paragraph("(These were fully paginated — no posts missed)")

        os.makedirs(self.output_dir, exist_ok=True)
        tier_label = f"_{os.environ.get('TIER_NAME', '')}" if os.environ.get('TIER_NAME') else ""
        filename = f"ThreadVault_DailyIntel_{datetime.now().strftime('%Y-%m-%d')}{tier_label}_{len(self.db)}communities_{len(all_posts)}viral.docx"
        filepath = os.path.join(self.output_dir, filename)
        doc.save(filepath)
        return os.path.abspath(filepath)

async def run_daily_intelligence(
    watchlist_path: str = None, 
    output_dir: str = "./outputs",
    lookback_hours: Optional[int] = None,
    viral_threshold: Optional[float] = None,
    test_mode: bool = False,
    test_subreddits: list = None,
    skip_ai: bool = False,
    db_path: str = None,
    tracking_path: str = None,
    tier_name: str = ""
) -> str:
    SEP = "─" * 55
    import time as _time

    pipeline = DailyIntelligencePipeline(output_dir, db_path=db_path, tracking_path=tracking_path)
    
    print(SEP)
    if test_mode and test_subreddits:
        print(f"[INIT] Test mode — loading {len(test_subreddits)} subreddits directly")
        # ⚠️ CRITICAL: redirect tracking to a separate file so the real
        # post_tracking.json (used by the production nightly run) is NEVER touched.
        pipeline.tracking_path = os.path.join(output_dir, "post_tracking_TEST.json")
        pipeline.db = [{"name": sub, "subscribers": 50000} for sub in test_subreddits]
        pipeline.stats["total_in_db"] = len(pipeline.db)
        pipeline.cleanup_tracking_db()
    else:
        print("[INIT] Loading community database...")
        await pipeline.initialize_db()
    print(f"[INIT] ✅ Database ready — {pipeline.stats['total_in_db']} communities to scan")
    print(SEP)

    async with httpx.AsyncClient() as client:
        # Stage 1
        print("[STAGE 1] Scanning communities for new viral posts (Pass A)...")
        t1 = _time.monotonic()
        await pipeline.run_stage_1(client)
        print(f"[STAGE 1] ✅ Done in {_time.monotonic()-t1:.1f}s")
        print(f"          New posts ingested : {pipeline.stats['new_posts_intake']}")
        print(f"          Total tracked      : {pipeline.stats['total_tracked']}")
        print(SEP)

        # Stage 2
        print("[STAGE 2] Running velocity scoring (Pass B — ranking candidates)...")
        t2 = _time.monotonic()
        candidates = pipeline.run_stage_2()
        print(f"[STAGE 2] ✅ Done in {_time.monotonic()-t2:.1f}s")
        print(f"          Candidates selected: {len(candidates)}")
        for p in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            cnt = sum(1 for c in candidates if c.get("priority") == p)
            if cnt:
                print(f"            {p:<8}: {cnt}")
        print(SEP)

        # Stage 3
        print("[STAGE 3] Fetching full post context from Arctic Shift...")
        t3 = _time.monotonic()
        await pipeline.run_stage_3(client, candidates)
        print(f"[STAGE 3] ✅ Done in {_time.monotonic()-t3:.1f}s")
        print(SEP)

        # Stage 4
        if skip_ai:
            print("[STAGE 4] AI analysis: SKIPPED (test mode without AI)")
        else:
            print("[STAGE 4] Running Gemini AI analysis on CRITICAL/HIGH candidates...")
        t4 = _time.monotonic()
        await pipeline.run_stage_4(candidates, skip_ai=skip_ai)
        print(f"[STAGE 4] ✅ Done in {_time.monotonic()-t4:.1f}s")
        print(SEP)

        # Stage 5
        print("[STAGE 5] Generating DOCX intelligence report...")
        t5 = _time.monotonic()
        out_path = pipeline.run_stage_5(candidates, test_mode=test_mode)
        size_kb = round(os.path.getsize(out_path) / 1024)
        print(f"[STAGE 5] ✅ Done in {_time.monotonic()-t5:.1f}s")
        print(f"          Report saved : {out_path}")
        print(f"          File size    : {size_kb} KB")
        print(SEP)

        # Write pipeline_stats.json — read by the workflow to build the GitHub Step Summary
        priority_counts = {}
        for p in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            cnt = sum(1 for c in candidates if c.get("priority") == p)
            if cnt:
                priority_counts[p] = cnt

        stats_payload = {
            "run_date":          datetime.now(timezone.utc).isoformat(),
            "mode":              "TEST" if test_mode else "PRODUCTION",
            "ai_analysis":       "skipped" if skip_ai else "enabled",
            "communities_in_db": pipeline.stats["total_in_db"],
            "posts_tracked":     pipeline.stats["total_tracked"],
            "new_posts_ingested":pipeline.stats["new_posts_intake"],
            "candidates_found":  len(candidates),
            "priority_breakdown":priority_counts,
            "peaked_today":      pipeline.stats.get("peaked_today", 0),
            "report_file":       os.path.basename(out_path),
            "report_size_kb":    size_kb,
            "pass_a_seconds":    round(pipeline.stats.get("pass_a_duration", 0)),
            "pass_b_seconds":    round(pipeline.stats.get("pass_b_duration", 0)),
        }
        stats_path = os.path.join(output_dir, "pipeline_stats.json")
        os.makedirs(output_dir, exist_ok=True)
        with open(stats_path, "w", encoding="utf-8") as f:
            json.dump(stats_payload, f, indent=2)
        print(f"[STATS] Health summary written to {stats_path}")

        return out_path

if __name__ == "__main__":
    asyncio.run(run_daily_intelligence())

